### ISSUE TITLE
allow for more poster content than just videos

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#171]
The original assumption was that all "posters" would be in video format. We now expect a variety of formats, potentially including: 
  * videos
  * images
  * linked documents
  * any combination of these

We should re-think the data structure for posters and their layouts to allow for this whole range of possibilities. My first thought is an array that defines elements in order they should display, e.g.
```
session-contents:
 - type: video
   url: https://youtube.com/v/id
   title: Intro Video
 - type: image
   url: /img/my-great-poster.png
   title: How we done it good in the COVID Times

```
I'm also imagining that we might want a similar "supplemental documents" array for "handouts" and the like -- not "displayed" as such, but little links at the bottom for downloadable content or links to web pages, e.g.:
```
supplemental-docs:
 - type: document
   url: /docs/my-handout.pdf
   title: Sample Handout
 - type: website
   url: https://example.com/nifty-widget
   title: NiftyWidget we used to make it better!
   alt: "What ever descriptive text is needed"
   accompanying-text: "<ul><li>Some Items</li><li>More Items</li></ul>"
```
I'm imagining that the title might get used as a caption, and that the accompanying-text would get an aria-labelledby / aria-label relation to the image for accessibility purposes. 

I propose that we talk about this at our next meeting (8/24)
