### ISSUE TITLE
new data element? pronouns for team & speakers

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#22]
I saw that at least one of our CPC team include pronouns in the request for photos and personal data. It doesn't look like Zeppelin includes a field for that, but perhaps we can add one both to the data files and to the data displays. 

This could apply to the `_data/team.yml` and `_data/speakers.yml` files.

On the data side, Jekyll supports arbitrarily adding a new data field, e.g.: 
```
  id: 1
  name: "Ken"
  surname: "Irwin"
  title: "Web Services Librarian - Miami University"
  pronouns: "he/him/his"
  thumbnailUrl: 
  team: true
  ribbon:
    - {abbr: "", title: ""}
  social:
    - {name: "twitter", link: "https://twitter.com/irwin_ken"}
    - {name: "github", link: "https://github.com/kenirwin"}
    - {name: "site", link: "https://kenirwin.net"}
```

On the display side, we could make some choices about how that info displays in various circumstances.
